### ISSUE TITLE
关于面板对dashboard参数的支持

### ISSUE THREAD

**Issue by zhaowwwjian** [lework/grafana-lenav-panel#1]
您好，近期我正在用grafana做金融方面的统计，因内容庞大，您的导航栏是一个很好的东西。但有个问题，link跳转无法适用于dashboard里的全局变量。这让我很苦恼。请问您是否能做适当改进以支持$Param 。谢谢。

**Comment by zhaowwwjian** [comment]
另外我报一个bug吧

IndexSizeError: Failed to execute 'setStart' on 'Range': There is no child at offset 41.

    at t (http://ip/public/build/7889.af8f3a231daca19ff375.js:2:93518)
    at t (http://ip/public/build/7889.af8f3a231daca19ff375.js:2:127338)


抱歉无法给予截图

**Comment by zhaowwwjian** [comment]
您好，能给予个回复么。谢谢

**Comment by lework** [comment]
抱歉，最近比较忙，这个需求我记下了，后面更新的时候我会修复掉。

**Comment by zhaowwwjian** [comment]
好的谢谢 期待您的更新

**Comment by lework** [comment]
@zhaowwwjian 新版本已支持
